### ISSUE TITLE
zip of older version available

### ISSUE THREAD

**Issue by adnub** [FaultyFunctions/GShade-Block#1]
Finally got fed up today after the latest update, but I was dumb and updated to v4.1.0 before checking if there was a way to disable the update check.

As far as I can tell, those links are no longer there in version 4.1.0 (at least using the Linux installer, where dxgi.dll is a symlink to GShade64.dll). Or at least I am unable to find them when looking through the file.

Is there any place where I can download an older version to check?

**Comment by adnub** [comment]
Just managed to get a hold of version 4.0.4 and those strings don't appear to be in there either, unless I'm looking in the wrong place.

**Comment by FaultyFunctions** [comment]
I'll take a look into this today and will update!

**Comment by FaultyFunctions** [comment]
Hmm it seems they have tried to patch this workaround or whatever changes they made to the update has changed how versions are loaded in, but knowing them it was probably the former.. I will look for an alternative way to go about this.

**Comment by FaultyFunctions** [comment]
Yeah they patched the workaround for versions above 4.0.4 and the only way I've found that works is to download an older version of `GShade64.dll` which is already fixed and replace your own version of it. I have made a link to download that version in the readme and have already tested it with someone that was using a patched version.
