### ISSUE TITLE
Requesting 3.4.0

### ISSUE THREAD

**Issue by iDevLA** [FaultyFunctions/GShade-Block#2]
Hello can we please get a 3.4.0? This one runs flawlessly and I refuse to jump now after they finally disabled it just two months ago. 

EDIT: NVM went ahead and did it myself. Here's 3.4.0 for anyone that needs it

68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 77 00 77 00 77 00 2E 00 67 00 6F 00 6F 00 67 00 6C 00 65 00 2E 00 63 00 6F 00 6D 00 00 00 00 00 68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 64 00 75 00 63 00 6B 00 64 00 75 00 63 00 6B 00 67 00 6F 00 2E 00 63 00 6F 00 6D 00 00 00 00 00 68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 30 00 2E 00 30 00 2E 00 30 00 2E 00 30 00 2F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 70 00 61 00 73 00 74 00 65 00 62 00 69 00 6E 00 2E 00 63 00 6F 00 6D 00 2F 00 72 00 61 00 77 00 2F 00 57 00 4B 00 6E 00 34 00 76 00 64 00 78 00 64 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by FaultyFunctions** [comment]
My bad didn't see this! Thanks for going through the effort of posting the fix for v3.4.0! I've added it to the repo! Thanks again!

**Comment by iDevLA** [comment]
> 

You’re welcome. Thank you for looking into this in the first place!
