### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Vulcan013** [FaultyFunctions/GShade-Block#3]
How do I make this work if I don't have a dxgi.dll in my game folder? I'm not on FF14 I'm on Phantasy Star Online 2: New Genesis and it doesn't have this file...

**Comment by FaultyFunctions** [comment]
With the recent controversy surrounding GShade ([see here](https://www.reddit.com/r/ffxiv/comments/10vdvbw/comment/j7gxddo/?utm_source=share&utm_medium=web2x&context=3)). I'd recommend alternatives to GShade like Reshade or Nividia filters (note that some presets might not work with default reshade?), though if you still want to go through with this what version of GShade are you on?

If it is before 4.0.4 this may still be possible. Do you have any files that are labelled as `d3d11.dll` or `d3d9.dll`? If so, you would use those instead. (It might work exactly as the guide says but I'm not 100% sure what GShade for PSO2 uses and how it might differ).

If you can't get it to work you can send me that `.dll` file and I can try to take a look and see if I can edit it manually for you.

**Comment by Vulcan013** [comment]
Well I actually just looked through my downloads and saw I had a version of GShade v3.0.1 in my History, I used Revo Uninstaller to purge my 4.1.0 GShade and reinstalled this. Though I noticed these patches don't go back that far, would I even need it with that version?

Edit: I also have a version of v4.0.1 also and that one is listed.

Edit2: Okay I think I managed to use v4.0.1 and used your method on the main page using the code I just hope it works when I boot it up

Edit3: Working and functional now I feel bad that I even posting here when I solved my own problem.... for what ever reason the dxgi.dll actually showed up in PSO2's folder this time around and I was able to do exactly as you stated. I'm half tempted to share the file just so others can follow suit. The GShade devs are petty...

**Comment by FaultyFunctions** [comment]
I'm glad you got it figured out! If anyone asks about PSO2 I'll direct them to this thread. I think the `GShade64.dll` file I link to the README would also work for PSO2 since the `dxgi.dll` file is technically just a symlink that links to `GShade64.dll` in the GShade folder. I'm closing this issue out but feel free to open it if you have any other questions!
