### ISSUE TITLE
how do I use the byte sequence files in the repo?

### ISSUE THREAD

**Issue by suchipi** [FaultyFunctions/GShade-Block#5]
I'm trying to patch my own 3.5.0 using the instructions in the readme, but I can't find the same URLs in the file. So I thought maybe I'd try using one of the versions there's a file for in the repo instead, by using one of the files in the repo. But it's not clear how or where to apply those byte sequences.

Are they meant to be loaded into a program? Or are you supposed to copy-paste that entire byte sequence into the dll? If so, how do I know what offset to paste it at?

Thanks

**Comment by FaultyFunctions** [comment]
When you searched for the URLs in the file did you change the search settings like it is shown in the image on the README?

Otherwise if you could perhaps upload your DLL file I can try to take a look for you!

**Comment by suchipi** [comment]
I was using a different hex editor ("Blessed", on Linux), but I was pretty sure I was using equivalent settings...

I ended up just using the patched 4.0.4 [from the readme](https://drive.google.com/file/d/1aruvRyQ6uxxoK1p_DsAa7nF-mJLRIfVQ/view?usp=share_link).
