### ISSUE TITLE
3.5.0 update block?

### ISSUE THREAD

**Issue by aberrateshade** [FaultyFunctions/GShade-Block#6]
For some reason the method doesn't seem to work with 3.5.0 so would there be another way to do so?? Reshade has been causing quite the problem and this is the only one I can salvage without relying on the risk of 5.0.2 and beyond, with the main roadblock being that of the update effect disabler. :(

**Comment by FaultyFunctions** [comment]
Hello! It's been a great while since I've looked at this. Could you try this block:
```
68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 30 00 2E 00 30 00 2E 00 30 00 2E 00 30 00 2F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 68 00 74 00 74 00 70 00 73 00 3A 00 2F 00 2F 00 70 00 61 00 73 00 74 00 65 00 62 00 69 00 6E 00 2E 00 63 00 6F 00 6D 00 2F 00 72 00 61 00 77 00 2F 00 46 00 74 00 31 00 43 00 37 00 66 00 72 00 75 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

Let me know if that works, thanks!

**Comment by aberrateshade** [comment]
Oh wow, it works!
It's just that the blocks to replace are different even if the https for both remains the same like so (from 0035FB70 to 0035FC30):
![image_2024-06-08_230042185](https://github.com/FaultyFunctions/GShade-Block/assets/171675061/70ddc6f7-722a-4a2a-bf57-192f50ea3ec3)

With that being said, by the looks of it, you can't use the 4.0.4 downgrade with the 5.0.0 launchers.

**HOWEVER**, in my trying to make it work, replacing the Gshade64.dll in the Gshade program files with the 4.0.4 version provided for 4.1.1 etc. and reinstalling the respective games seemed to actually make the Gshade think it went from 3.5.0 to 4.0.4! Missing some shaders, but nothing too major. I'll try it again to doublecheck if it works.

Could be nice if we had a 3.5.0 download straight, but I do suppose that's what social sites are for.
Thanks!

**Comment by aberrateshade** [comment]
![image](https://github.com/FaultyFunctions/GShade-Block/assets/171675061/54b3bedc-fc87-4567-a3b5-13b5ebfa2ad5)

It does, though I'm not sure if it'll connect to FFXIV once DT hits.
